

/* Create Tables */

CREATE TABLE ACADEMY_COURSES
(
	COURSE_NO number(4,0) NOT NULL,
	COURSE_NAME varchar2(255) NOT NULL,
	COURSE_QUATO number(3,0) NOT NULL,
	COURSE_REQ_CNT number(3,0) DEFAULT 0,
	COURSE_STATUS varchar2(100) DEFAULT '모집중',
	COURSE_CREATE_DATE date DEFAULT SYSDATE,
	TEACHER_ID varchar2(20) NOT NULL,
	PRIMARY KEY (COURSE_NO)
);


CREATE TABLE ACADEMY_COURSE_REGISTRATIONS
(
	REG_NO number(4,0) NOT NULL,
	STUDENT_ID varchar2(20) NOT NULL,
	COURSE_NO number(4,0) NOT NULL,
	REG_CANCELED char(1) DEFAULT 'N',
	REG_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (REG_NO)
);


CREATE TABLE ACADEMY_STUDENTS
(
	STUDENT_ID varchar2(20) NOT NULL,
	STUDENT_PASSWORD varchar2(20) NOT NULL,
	STUDENT_NAME varchar2(20) NOT NULL,
	STUDENT_PHONE varchar2(20) NOT NULL,
	STUDENT_EMAIL varchar2(100) NOT NULL,
	STUDENT_DELETED char(1) DEFAULT 'N',
	STUDENT_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (STUDENT_ID)
);


CREATE TABLE ACADEMY_TEACHER
(
	TEACHER_ID varchar2(20) NOT NULL,
	TEACHER_PASSWORD varchar2(20) NOT NULL,
	TEACHER_NAME varchar2(20) NOT NULL,
	TEACHER_PHONE varchar2(20) NOT NULL,
	TEACHER_EMAIL varchar2(100),
	TEACHER_SALARY number(8) NOT NULL,
	TEACHER_RETIRED char(1) DEFAULT 'N',
	TEACHER_CREATE_DATE date DEFAULT SYSDATE,
	PRIMARY KEY (TEACHER_ID)
);



/* Create Foreign Keys */

ALTER TABLE ACADEMY_COURSE_REGISTRATIONS
	ADD FOREIGN KEY (COURSE_NO)
	REFERENCES ACADEMY_COURSES (COURSE_NO)
;


ALTER TABLE ACADEMY_COURSE_REGISTRATIONS
	ADD FOREIGN KEY (STUDENT_ID)
	REFERENCES ACADEMY_STUDENTS (STUDENT_ID)
;


ALTER TABLE ACADEMY_COURSES
	ADD FOREIGN KEY (TEACHER_ID)
	REFERENCES ACADEMY_TEACHER (TEACHER_ID)
;



